[project]
name = "visx_downloader"
version = "2.0"
description = "a simple python script to download visx"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
    "tqdm>=4.67.1",
    "typer>=0.16.0",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.12.0",
]
